### PR TITLE
Feature/rdss 898 travis data model automation

### PR DESCRIPTION
**Pull request by steph-digirati**
Added a travis build job to recreate the documentation on any update to the source.  This creates the markdown files and diagrams for logical and concept models and pushes the generated files back into the repo.

### CODE REVIEW

**Comment by steph-digirati** [comment]
The markdown was previously being entirely created manually.  The use of mdgen allows it to be created from the model itself and removes the separate task.  

Currently the model only has some of the entities and fields populated but those that are produce markdown that is like the manually created markdown.

Diagrams were a future task but it was a simple command to produce them.

**Comment by Jenniferstrej** [comment]
Where are the markdowns created in this line https://github.com/JiscRDSS/rdss-canonical-data-model/blob/feature/RDSS-898-travis-data-model-automation/deploy.sh#L24?

**Comment by steph-digirati** [comment]
They are created in the location named after the -o argument.  The "markdown" directory.

**Comment by Jenniferstrej** [comment]
Yes, right, I was looking at the wrong place, sorry.

**Comment by Jenniferstrej** [comment]
If the input for generation of those diagrams and markdowns is supposed to be metadata-json files (.mdj) I will approve this PR.

**Pull request merged**
